[module]
[module.hugoVersion]
extended = true
min = "0.87.0"
max = "0.131.0"


[params.giscus]
    data-repo="Wercurial/Wercurial.github.io"
    data-repo-id="MDEwOlJlcG9zaXRvcnkxNzQ5NDg5Mjc="
    data-category="Announcements"
    data-category-id="DIC_kwDOCm2CP84CiHCH"
    data-mapping="pathname"
    data-strict="0"
    data-reactions-enabled="1"
    data-emit-metadata="0"
    data-input-position="top"
    data-theme="preferred_color_scheme"
    data-lang="zh-CN"
    data-loading="lazy"
    crossorigin="anonymous"


